### ISSUE TITLE
A big THANK YOU!!!

### ISSUE THREAD

**Issue by 2play** [pcercuei/kmsgrab#1]
@pcercuei Hi Paul!
The tool i was looking for!
So simple and great that does everything I wanted and other tools are not capable of!
Just wanted to say thank you!

You can close anytime

**Comment by 2play** [comment]
If i may suggest jpg will create smaller size images.
If you can do an updated version it will be great otherwise i have a script to so after grab.

I'll use your tool on my Rockpro64 and Tinkerboard PlayBox releases and have you on the ThankYou script

**Comment by pcercuei** [comment]
Glad it could be of any help.

About jpeg - if you send a PR then I'll merge it ;) The default should still be PNG though, because it's lossless, and you generally want that for screen captures.
