### ISSUE TITLE
x86 Linux error

### ISSUE THREAD

**Issue by 2play** [pcercuei/kmsgrab#4]
hello @pcercuei Paul
i have compiled/installed your great  tool on a new Armbian 24.2.4 Jammy installation.
So far i tested on similar but arm based installations.
This time is on x86 Intel J4125 CPU with above OS 
Initially I got error "Unable to mmap prime buffer"
I made sure all dependencies are installed ( libpng-dev libdrm-dev ) and retried

Today I get below results:
![printscreen03_26_2024--h09-m13-s22](https://github.com/pcercuei/kmsgrab/assets/30235736/5d88f072-0b95-4046-92a4-86cfccbf2cd4)
![printscreen03_26_2024--h09-m45-s53](https://github.com/pcercuei/kmsgrab/assets/30235736/725e6f6c-94fb-4d62-82a1-09417a489550)

I can attach the binary also.
I have been using your tool with success last couple years but cant on this setup
Please let me know what to test or update

**Comment by pcercuei** [comment]
That's the exact same problem as in #2 so I'll close this ticket.

As for why it happens, I don't know; and I am not planning to debug it further.
